name: __projectName__
description: A web app that uses AngularDart Components
# version: 0.0.
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  ngcomponents: ^1.0.2

dev_dependencies:
  angular_test: ^4.0.1
  build_runner: ^2.1.7
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
  lints: ^1.0.1
  meta: ^1.7.0
  test: ^1.6.3
