name: __projectName__
description: A web app that uses AngularDart Components
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ngdart: ^7.1.1
  ngcomponents: ^1.2.0

dev_dependencies:
  ngtest: ^4.1.1
  build_runner: ^2.2.0
  build_version: ^2.1.1
  build_test: ^2.1.5
  build_web_compilers: ^3.2.4
  lints: ^1.0.1
  test: ^1.21.0
